version: '3.8'

services:

  node-ms-mongodb:
    image: mongo
    container_name: node-ms-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    env_file: 
    - .env
    ports:
      - '27017-27019:27017-27019'
    volumes: 
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./backend/mongo-data:/data/db
    networks:
      - node-ms-network
    restart: always

  node-ms-mongo-express:
    image: mongo-express
    container_name: node-ms-mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=${DATABASE_DOCKER_HOST}
      - ME_CONFIG_MONGODB_PORT=${DATABASE_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${DATABASE_NAME}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${DATABASE_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${DATABASE_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    env_file: 
      - .env
    volumes:
      - ./backend/sleep.sh:/sleep.sh:ro
    command: /bin/sh -c "/sleep.sh && tini -- /docker-entrypoint.sh"
    networks:
      - node-ms-network
    depends_on:
      - node-ms-mongodb
    restart: always

  node-ms-backend:
    image: node-ms-backend
    container_name: node-ms-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: /bin/sh -c "/workspace/backend/sleep.sh && exec node src/server.js"
    ports:
      - 4000:4000
      - 9229:9229
    env_file: .env
    environment:
      NODE_ENV: ${development}
      APP_PORT: ${APP_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_DOCKER_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - ./backend/:/workspace/backend
      - /workspace/backend/node_modules
    networks:
      - node-ms-network
    restart: on-failure
    depends_on:
      - node-ms-mongodb
    deploy:
      replicas: 1

  node-ms-frontend:
    image: node-ms-frontend
    container_name: node-ms-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    env_file: .env
    environment:
      NODE_ENV: ${development}
    volumes:
      - ./frontend/:/workspace/frontend
      - /workspace/frontend/node_modules
    networks:
      - node-ms-network
    restart: on-failure
    deploy:
      replicas: 1

networks:
    node-ms-network:
      driver: bridge
      name: node-ms-network