apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ms-mongodb-deployment
  labels:
    app: node-ms-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-ms-mongodb
  template:
    metadata:
      labels:
        app: node-ms-mongodb
    spec:
      containers:
      - name: node-ms-mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: node-ms-mongodb
        # volumeMounts:
        #   - name: storage
        #     mountPath: /data/db
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
      # volumes:
      #   - name: storage
      #     persistentVolumeClaim:
      #       claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node-ms-mongodb-service
spec:
  selector:
    app: node-ms-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 256Mi